FROM srikanthlogic/bionic-nodejs

MAINTAINER Srikanth <srik@srik.me>

RUN \
  apt-get update && \
  apt-get install -y python python-dev python-pip python-virtualenv && \
  rm -rf /var/lib/apt/lists/*
